#!/bin/bash
for port in {8000..9000}; do
if ! netstat -tln 2>/dev/null | grep -q "[: ]$port[ :]"
then
python -m SimpleHttpServer $port
  if [ $? -ne 0 ]
  then
  python3 -m http.server $port
    if [ $? -ne 0 ]
    then
    python -m http.server $port
    exit
    fi
  fi
exit
fi

done
