# Variables required for RPi-Scripts Installation
#
### Scripts to Install ###
# a-j  [NOTE: CAN'T USE "i"]
# when adding more, must update "install-[num]-lists.sh"
a=activeservices.list
b=allpackages.list
c=allservices.list
d=hostip.list
e=makewebserver
f=matrix.sh
g=systemctlenabled.list
h=temp.sh
j=usergrp.list
#
# this is what you want to call it in /bin/
a1=activeservices
b1=allpackages
c1=allservices
d1=hostip
e1=makewebserver
f1=matrix
g1=systemctlenabled
h1=temp
j1=usergrp
#############################################
### sets sleep functions ###
s () { sleep .5; }
s1 () { sleep 1; }
s2 () { sleep 2; }
s3 () { sleep 3; }
s4 () { sleep 4; }
s5 () { sleep 5; }
#
#############################################
### variables for current date ###
currentDate=$(date "+%m-%d-%Y")
repeatDate=$(date "+%m-%d-%Y.%T")
#
#############################################
### variables for files/directories ###
dir=`pwd`
userHome=$(eval echo "~$SUDO_USER")
scripts=$userHome/scripts
bin=/bin/
gitDir="RPi-Scripts-Scripts"
scriptsDir="RPI-Scripts"
gitDL="Scripts.zip"
gitLink=$(curl -s https://api.github.com/repos/TROUBLESOM0/RPi-Scripts/releases/latest | grep "zipball_url" | cut -d '"' -f 4)
# #FOR TESTING ONLY# gitLink=~/Public/Scripts.zip
#
#############################################
###            repeat characters          ###
# example: char_repeat 25 "-"
# repeats "-" 25 times
function char_repeat() {
count="$1"
char="$2"
for (( i=0; i < $count; ++i ))
do printf "$char"
done
echo
}
#
#############################################
###              delay dots               ###
function dot_delay() {
for (( i=0; i < 25; ++i ))
do printf "."
  sleep .1
done
echo
}
